### ISSUE TITLE
Shale Hills two-grid model land cover type

### ISSUE THREAD

**Issue by shiyuning** [PSUmodeling/PIHM-Simulations#3]
In the [.att file](https://github.com/PSUmodeling/PIHM-Simulations/blob/master/ShaleHills_twogrids/ShaleHills_twogrids.att), it shows that the two model grids are assigned with land cover type 41, which does not exist in the default land cover description file. What should we do?

**Comment by WeiZhiWater** [comment]
> In the [.att file](https://github.com/PSUmodeling/PIHM-Simulations/blob/master/ShaleHills_twogrids/ShaleHills_twogrids.att), it shows that the two model grids are assigned with land cover type 41, which does not exist in the default land cover description file. What should we do?

I forgot to mention that the type 41 is the one made by Hang. Perhaps we can update the vegprmt.tbl?

**Comment by shiyuning** [comment]
We had this discussion before and I believe that generating a Type 41 by averaging different land cover type parameters does not make sense because the model does not respond linearly to those parameters. I suggest using the dominant land cover type.

**Comment by whang126** [comment]
I think if we are going to use the two-grid case of Shale Hills as a default example for the package, the dominant land cover type may be a better option, which may avoid confusion. 

For myself, I still think averaging parameter values is one of typical approaches used for homogenizing/upscaling. Usually we don't know how these parameters change with scales.

**Comment by lili-psu** [comment]
I think it might be ok for Shale Hills to use the dominant type, because the plants are not that different and it is a small catchment. But if we work on a much larger catchment with much more diverse vegetation with no clear dominant vegetation, for example, ~30% of each type with 3-4 major types, then it is hard to justify the "using the dominant" approach. 

Yuning, when you say there may be problems with a newly defined vegetation type, what are the exact problems? my understanding is that the code reads in the numbers and do the calculation. How does it differ from the numbers within the 40 types in the original database?

**Comment by shiyuning** [comment]
@lili-psu One problem is that the 40-type vegetation parameter file is provided with source code. If people just download the ShaleHills two grid input folder but use the stock version source code, they won't be able to run it because their source code does not have 41 land cover types.

Another problem is that the land surface does not respond linearly to those parameters. So averaging them does not make sense. A proper way to represent multiple land use types is to run the land surface module multiple times, each time with one land use type, and then averaging the results by spatial area fraction.

**Comment by lili-psu** [comment]
Yuning, i meant to send more comments about this. i don't think this discussion is closed. I am not sure what you mean by saying have multiple land use runs? how would that help representing an "averaged" watershed? this would mean if we do calibration we need to run 3 sets of calibration for each dominant land use type? and then have 3 sets of calibration parameters? I don't see why this is necessary and helpful. 

Can you change in the stock version code to be able to read in more land use types. To me that veg file is really a database. As long as you enable the reading of additional land use type it does not matter that much. Each type has its own set of parameters, including the averaged ones like type 41. we have been doing this a lot in our geochemical database. There is a default database but we can alway add additional representative minerals that are not real but representing some "model mineral". Can we do something similar like this? thanks.
